### ISSUE TITLE
Paginação

### ISSUE THREAD

**Issue by Maegima** [UnifespCodeLab/plasmedis-api#21]
# História de Usuário

O usuário quer retornar um número reduzido de entradas quando faz um requisição a um endpoint que retorna uma lista.

# Resumo

Deve ser definido o modelo de paginação utilizado para retornar listas pela API.

# Critérios de Aceite

- [ ] Definir modelo de retorno padrão para retorno de listas (--)
- [ ] Documentar o modelo de retorno de listas (--)
- [ ] Aplicar modelo de paginação para Usuários (--)
- [ ] Aplicar modelo de paginação para Postagens (--)
- [ ] Aplicar modelo de paginação para Comentários (--)
- [ ] Aplicar modelo de paginação para Formulários (--)
- [ ] Aplicar modelo de paginação para Bairros (--)
- [ ] Aplicar modelo de paginação para Privilégios (--)

# Protótipo

# Informações Adicionais
