### ISSUE TITLE
Documentar

### ISSUE THREAD

**Issue by Maegima** [UnifespCodeLab/plasmedis-api#27]
# História de Usuário

O usuário quer ter uma forma fácil de obter a lista de endpoints da API.

# Resumo

Hoje não existe uma documentação que lista os endpoints da API e suas entradas e saídas.

# Critérios de Aceite

- [x] Documentar Controller Neighborhoods (#14)
- [x] Documentar Controller Categories (#15)
- [x] Documentar Controller Posts (#16)
- [x] Documentar Controller Forms (#17)
- [x] Documentar Controller Comments (#18)

# Protótipo

# Informações Adicionais
